name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      deluge:
        image: lscr.io/linuxserver/deluge:latest
        env:
          PUID: 1000
          PGID: 1000
          TZ: Etc/UTC
        ports:
          - '8112:8112'
          - '6881:6881'
          - '6881:6881/udp'
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # https://github.com/wyvox/action-setup-pnpm
      - uses: wyvox/action-setup-pnpm@d84148cd87d55adb709e92120c709b88d15bceac # v4.0.0
        with:
          node-version: 26

      - name: lint
        run: pnpm run lint

      - name: test
        run: pnpm run test
